package com.fantasy.model;

public enum Team {

    GT,CHE,PBKS,KOL,MI,
    SCO,ZIM,AUS,NZ,ENG,AFG,SL,IRE,IND,PAK,BAN,NED,SA,LIO,WEP,
    MIW,UPW,WI,GOR,GAM,
    SWH,BEL,STA,AMR,QUT,CHU,THR,CTB,ND,AZA,BOB,THU,CCH,FBA,DAT,GGI,PRL,JOH,KHT,RAN,KHW
}
